services:
  # Backend service (Rails)
  backend:
    build:
      context: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/rails
    ports:
    # host_port: container_port
      - "3000:3000"
    depends_on:
      - db
      - elasticsearch
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/GearMate_development
      RAILS_ENV: development
    env_file:
      - .env
    
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.11
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


  # Frontend service (React)
  frontend:
    build:
      context: ./client
    volumes:
      - ./client:/client
      - node_modules:/client/node_modules
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    command: npm run dev -- --host

  # PostgreSQL database service
  db:
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: GearMate_development
    ports:
      - "5432:5432"

# Persistent storage for the PostgreSQL database
volumes:
  pgdata:
  node_modules:
  es_data: